name: Sync Modules

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  check-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install axios

      - name: Run Sync Script
        run: node scripts/sync.js
        shell: node
